{
 "title": "Streamiz",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "streamiz_app_id",
    "label": "Streamiz Application",
    "query": {
     "query": "label_values(stream_metrics_application_id, application_id)"
    }
   },
   {
    "name": "streamiz_thread_id",
    "label": "Streamiz Thread",
    "query": {
     "query": "label_values(stream_thread_metrics_thread_start_time, thread_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State stores Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_fetch_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Fetch Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_fetch_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Fetch Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "stream_state_metrics_fetch_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Get Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_get_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Get Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_get_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Get Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "stream_state_metrics_get_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "All Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_all_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "All Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_all_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "All Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "stream_state_metrics_all_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Range Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_range_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Range Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_range_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Range Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "expr": "stream_state_metrics_range_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_put_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_put_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "expr": "stream_state_metrics_put_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put All Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_put_all_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put All Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_put_all_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put All Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "stream_state_metrics_put_all_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put If Absent Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_put_if_absent_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put If Absent Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_put_if_absent_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Put If Absent Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "targets": [
      {
       "expr": "stream_state_metrics_put_if_absent_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Flush Latency AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_flush_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}"
      }
     ]
    },
    {
     "title": "Flush Latency MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_state_metrics_flush_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Flush Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "targets": [
      {
       "expr": "stream_state_metrics_flush_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{rocksdb_window_state_id}}{{in_memory_window_state_id}}{{rocksdb_state_id}}{{in_memory_state_id}}-{{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasks Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Process Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_task_metrics_process_latency_avg{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "process-latency-avg-{{task_id}}"
      },
      {
       "expr": "stream_task_metrics_process_latency_max{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "process-latency-max-{{task_id}}"
      }
     ]
    },
    {
     "title": "Restoration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(stream_task_metrics_active_restoration{thread_id=\"$streamiz_thread_id\"})"
      }
     ]
    },
    {
     "title": "Task Commit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
     "targets": [
      {
       "expr": "stream_task_metrics_commit_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{task_id}}"
      }
     ]
    },
    {
     "title": "Process Total Records",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "stream_task_metrics_process_total{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{task_id}}"
      }
     ]
    },
    {
     "title": "Task Process Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "stream_task_metrics_process_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{task_id}}"
      }
     ]
    },
    {
     "title": "Active Buffer Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 10 },
     "targets": [
      {
       "expr": "stream_task_metrics_active_buffer_count{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "{{task_id}}"
      }
     ]
    },
    {
     "title": "Dropping Records",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
     "targets": [
      {
       "expr": "stream_task_metrics_dropped_records_rate{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "rate-{{task_id}}"
      },
      {
       "expr": "stream_task_metrics_dropped_records_total{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "total-{{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Number",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(stream_metrics_stream_threads{application_id=\"$streamiz_app_id\"})"
      }
     ]
    },
    {
     "title": "Topology",
     "type": "stat",
     "gridPos": { "h": 5, "w": 14, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(stream_metrics_topology_description{application_id=\"$streamiz_app_id\"}) by (topology_description)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "min(stream_metrics_state{application_id=\"$streamiz_app_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Number",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(stream_thread_metrics_task_created_total{thread_id=~\"$streamiz_app_id(.*)\"})"
      }
     ]
    },
    {
     "title": "Thread Poll Records AVG",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(stream_thread_metrics_poll_records_avg{thread_id=~\"$streamiz_app_id(.*)\"})"
      }
     ]
    },
    {
     "title": "Thread Process Records AVG",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "records" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(stream_thread_metrics_process_records_avg{thread_id=~\"$streamiz_app_id(.*)\"})"
      }
     ]
    },
    {
     "title": "Thread Process Rate AVG",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "records" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(stream_thread_metrics_process_rate_rate{thread_id=~\"$streamiz_app_id(.*)\"})"
      }
     ]
    },
    {
     "title": "Thread Process Latency AVG",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(stream_thread_metrics_process_latency_avg{thread_id=~\"$streamiz_app_id(.*)\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream Thread Start Time",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "stream_thread_metrics_thread_start_time{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Number of records polled",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "stream_thread_metrics_poll_total{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Number of records processed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 13, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "stream_thread_metrics_process_rate_total{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Commit Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stream_thread_metrics_commit_total{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Poll Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_poll_latency_avg{thread_id=\"$streamiz_thread_id\"}"
      },
      {
       "expr": "stream_thread_metrics_poll_latency_max{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_commit_latency_avg{thread_id=\"$streamiz_thread_id\"}"
      },
      {
       "expr": "stream_thread_metrics_commit_latency_max{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Process Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_process_latency_avg{thread_id=\"$streamiz_thread_id\"}"
      },
      {
       "expr": "stream_thread_metrics_process_latency_max{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Poll Records",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_poll_records_avg{thread_id=\"$streamiz_thread_id\"}"
      },
      {
       "expr": "stream_thread_metrics_poll_records_max{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Poll Records Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_poll_latency_max{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    },
    {
     "title": "Thread Ratio",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_commit_ratio{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "stream_thread_metrics_commit_ratio"
      },
      {
       "expr": "stream_thread_metrics_poll_ratio{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "stream_thread_metrics_poll_ratio"
      },
      {
       "expr": "stream_thread_metrics_process_ratio{thread_id=\"$streamiz_thread_id\"}",
       "legendFormat": "stream_thread_metrics_process_ratio"
      }
     ]
    },
    {
     "title": "Thread Commit Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "stream_thread_metrics_commit_rate{thread_id=\"$streamiz_thread_id\"}"
      }
     ]
    }
   ]
  }
 ]
}